# Generated by Django 3.0.8 on 2020-07-24 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('release_year', models.DateField()),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('aliases', models.CharField(blank=True, max_length=50, null=True, verbose_name='Aliases')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    choices=[('Actor/Actress', 'Actor/Actress'), ('Director', 'Director'), ('Producer', 'Producer')],
                    default='Actor/Actress', max_length=30, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'movies_role',
            },
        ),
        migrations.CreateModel(
            name='PersonRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_roles',
                                             to='movies.Person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_roles',
                                           to='movies.Role')),
            ],
            options={
                'db_table': 'movies_person_roles',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(related_name='people', through='movies.PersonRoles', to='movies.Role'),
        ),
        migrations.CreateModel(
            name='MoviePeopleRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_roles',
                                            to='movies.Movie')),
                ('person_role',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_movies',
                                   to='movies.PersonRoles')),
            ],
            options={
                'db_table': 'movies_movie_people_roles',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='people',
            field=models.ManyToManyField(related_name='movies', through='movies.MoviePeopleRoles',
                                         to='movies.PersonRoles'),
        ),
    ]
