# Generated by Django 3.0.8 on 2020-07-27 22:01
from __future__ import unicode_literals

from django.db import migrations


def create_default_values(apps, schema_editor):
    role = apps.get_model('movies', 'Role')

    role.objects.create(name='Actor/Actress')
    role.objects.create(name='Director')
    role.objects.create(name='Producer')


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_values),
    ]
