# Generated by Django 3.0.8 on 2020-08-04 18:50
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.admin import User


def create_superuser(apps, schema_editor):
    if not User.objects.filter(username='UserTest', is_superuser=True).exists():
        superuser = User()
        superuser.is_active = True
        superuser.is_superuser = True
        superuser.is_staff = True
        superuser.username = 'UserTest'
        superuser.email = 'info@example.com'
        superuser.set_password('Test@1234')
        superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_migration_default_roles'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]

