# Generated by Django 3.0.8 on 2020-08-04 22:43

from django.db import migrations
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_create_super_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movie',
            managers=[
                ('objects', movies.models.MovieManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('objects', movies.models.PersonManager()),
            ],
        ),
    ]
