# Generated by Django 3.0.8 on 2020-08-05 00:38

from django.db import migrations
from datetime import date


def populate_people_movies_data(apps, schema_editor):
    role = apps.get_model('movies', 'Role')
    person = apps.get_model('movies', 'Person')
    movie = apps.get_model('movies', 'Movie')

    person.objects.all().delete()
    movie.objects.all().delete()

    roles = list(role.objects.all().values_list('id', flat=True))

    star_war_staff = [
        {'first_name': 'Jeffrey', 'last_name': 'Abrams', 'roles': [roles[1], roles[2]]},
        {'first_name': 'Pippa', 'last_name': 'Anderson', 'roles': [roles[2]]},
        {'first_name': 'Carrie', 'last_name': 'Fisher', 'aliases': 'Leia Organa', 'roles': [roles[0]]},
        {'first_name': 'Mark', 'last_name': 'Hamill', 'aliases': 'Luke Skywalker', 'roles': [roles[0]]},
        {'first_name': 'Adam', 'last_name': 'Driver', 'aliases': 'Kylo Ren', 'roles': [roles[0]]}
    ]

    star_war_people = []

    for star_war_person in star_war_staff:
        if not isinstance(star_war_person, int):
            instance = person.objects.create_new_person(data=star_war_person)
            star_war_people.append(instance.id)

    star_war_movie = {
        'title': 'Star Wars: The Rise of Skywalker',
        'release_year': str(date(2019, 12, 16)),
        'people': star_war_people
    }

    movie.objects.create_new_movie(data=star_war_movie)

    the_expendables_staff = [
        {'first_name': 'Sylvester', 'last_name': 'Stallone', 'aliases': 'Barney Ross',
         'roles': [roles[0], roles[1]]},
        {'first_name': 'Guymon', 'last_name': 'Casady', 'roles': [roles[2]]},
        {'first_name': 'Jason', 'last_name': 'Statham', 'aliases': 'Lee Christmas', 'roles': [roles[0]]},
        {'first_name': 'Jet', 'last_name': 'Li', 'aliases': 'Yin Yang', 'roles': [roles[0]]},
        {'first_name': 'Dolph', 'last_name': 'Lundgren', 'aliases': 'Gunner Jensen', 'roles': [roles[0]]}
    ]

    the_expendables_people = []

    for expendable_person in the_expendables_staff:
        if not isinstance(expendable_person, int):
            instance = person.objects.create_new_person(data=expendable_person)
            the_expendables_people.append(instance.id)

    the_expendables_movie = {
        'title': 'The Expendables',
        'release_year': str(date(2010, 8, 3)),
        'people': the_expendables_people
    }

    movie.objects.create_new_movie(data=the_expendables_movie)


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200804_2243'),
    ]

    operations = [
        migrations.RunPython(populate_people_movies_data),
    ]
